=== BackupTheBerlios/ccaustin/calvary-cms/docs/usecases/usecases.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="actor" type="xs:string"/>
	<xs:element name="alternate-flow">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="event" ref="event" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="created-by" type="xs:string"/>
	<xs:element name="created-on" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="event" type="xs:string"/>
	<xs:element name="event-flow">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="event" ref="event" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="feature" type="xs:string"/>
	<xs:element name="goal" type="xs:string"/>
	<xs:element name="history">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="revision" ref="revision" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="note" type="xs:string"/>
	<xs:element name="notes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="note" ref="note" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="postcondition" type="xs:string"/>
	<xs:element name="postconditions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="postcondition" ref="postcondition" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="precondition" type="xs:string"/>
	<xs:element name="preconditions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="precondition" ref="precondition" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="priority" type="xs:string"/>
	<xs:element name="related-usecase" type="xs:string"/>
	<xs:element name="related-usecases">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="related-usecase" ref="related-usecase" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="revision">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="editor" type="xs:string" use="required"/>
					<xs:attribute name="date" type="xs:string" use="required"/>
					<xs:attribute name="version" use="required" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="usecase">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" ref="name"/>
				<xs:element name="created-by" ref="created-by"/>
				<xs:element name="created-on" ref="created-on"/>
				<xs:element name="priority" ref="priority"/>
				<xs:element name="actor" ref="actor"/>
				<xs:element name="feature" ref="feature"/>
				<xs:element name="goal" ref="goal"/>
				<xs:element name="description" ref="description"/>
				<xs:element name="notes" ref="notes" minOccurs="0" maxOccurs="1"/>
				<xs:element name="preconditions" ref="preconditions" minOccurs="0" maxOccurs="1"/>
				<xs:element name="postconditions" ref="postconditions" minOccurs="0" maxOccurs="1"/>
				<xs:element name="related-usecases" ref="related-usecases" minOccurs="0" maxOccurs="1"/>
				<xs:element name="event-flow" ref="event-flow"/>
				<xs:element name="alternate-flow" ref="alternate-flow" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="history" ref="history" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BackupTheBerlios/ccaustin/calvary-cms/docs/usecases/PublishSite.xml
<?xml version="1.0"?>
<!--?xml:stylesheet type="text/xsl"
                 href="usecases.xsl"
                 version="1.0"
                 encoding="UTF-8"?-->
<usecase id="PublishSite"
         xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="usecases.xsd">

  <name>Publish Site</name>
  <created-by>jwhigginbotham</created-by>
  <created-on>November 18 2002</created-on>
  <priority>High</priority>
  <actor>Name</actor>
  <feature>feature</feature>
  <goal>Goal...</goal>
  <description>Description...</description>
  <!-- Include any notes about this usecase that is out of scope of the rest of the doc
  <notes>
    <note>Notes and Issue 1...</note>
    <note>Notes and Issue 2...</note>
  </notes>
  -->
  <!-- Any preconditions required to be in place before the use case begins
  <preconditions>
    <precondition>precondition 1...</precondition>
    <precondition>precondition 2...</precondition>
  </preconditions>
  -->
  <!-- Any postconditions that will exist after the use case ends in the normal event flow
  <postconditions>
    <postcondition>postcondition 1...</postcondition>
    <postcondition>postcondition 2...</postcondition>
  </postconditions>
  -->
  <!-- Any related usecases (by usecase id)
  <related-usecases>
    <related-usecase>UC2.0</related-usecase>
    <related-usecase>UC3.0</related-usecase>
  </related-usecases>
  -->
  <!-- The standard event flow
  <event-flow>
    <event>Step 1...</event>
    <event>Step 2...</event>
  </event-flow>
  -->
  <!-- An alternate event flow
  <alternate-flow name="Alternate title...">
    <event>Step 1...</event>
    <event>Step 2...</event>
  </alternate-flow>
  -->
  <!-- Change history
  <history>
    <revision editor="jwh" date="Aug 27, 2001" version="1.1">Notes...</revision>
  </history>
  -->
</usecase>

=== BackupTheBerlios/ccaustin/calvary-cms/docs/usecases/CreateEvent.xml
<?xml version="1.0"?>
<!--?xml:stylesheet type="text/xsl"
                 href="usecases.xsl"
                 version="1.0"
                 encoding="UTF-8"?-->
<usecase id="CreateEvent"
         xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="usecases.xsd">

  <name>Create Event</name>
  <created-by>jwhigginbotham</created-by>
  <created-on>February 2 2003</created-on>
  <priority>High</priority>
  <actor>member</actor>
  <feature>contentmanagement</feature>
  <goal>Allow a registered member to create an event for approval and publishing</goal>
  <description>A registered member, such as a staff member of ministry servant, needs to post an
  event for an upcoming event (such as a retreat).</description>
  <!-- Include any notes about this usecase that is out of scope of the rest of the doc
  <notes>
    <note>Notes and Issue 1...</note>
    <note>Notes and Issue 2...</note>
  </notes>
  -->
  <!-- Any preconditions required to be in place before the use case begins
  -->
  <preconditions>
    <precondition>The member is currently logged in to the system</precondition>
    <precondition>The member has permission to create events</precondition>
  </preconditions>
  <!-- Any postconditions that will exist after the use case ends in the normal event flow
  -->
  <postconditions>
    <postcondition>An event is queued up for approval and later publishing</postcondition>
  </postconditions>
  <!-- Any related usecases (by usecase id)
  -->
  <related-usecases>
    <related-usecase>Login</related-usecase>
  </related-usecases>
  <!-- The standard event flow
  -->
  <event-flow>
    <event>The user selects 'submit an event'</event>
    <event>The user receives a form to submit an event</event>
    <event>The user enters the event information: event name, event description, starting date, ending date, time
    (optional), requested publication date (optional - default immediate on approval), and any associated
    ministries (1+ ministries that this event will appear on the ministry home page of).</event>
    <event>The system validates the data, and upon finding it valid, saves the data and informs the
    editorial staff that the event is ready for review.</event>
  </event-flow>
  <!-- An alternate event flow
  -->
  <alternate-flow name="Invalid Data Entered">
    <event>The user enters invalid event data</event>
    <event>The system shows the form again, prefilled with the user's entries and errors regarding
    each field that was in error</event>
  </alternate-flow>
  <!-- Change history
  <history>
    <revision editor="jwh" date="Aug 27, 2001" version="1.1">Notes...</revision>
  </history>
  -->
</usecase>

=== BackupTheBerlios/ccaustin/calvary-cms/docs/usecases/Login.xml
<?xml version="1.0"?>
<!--?xml:stylesheet type="text/xsl"
                 href="usecases.xsl"
                 version="1.0"
                 encoding="UTF-8"?-->
<usecase id="Login"
         xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="usecases.xsd">

  <name>Login</name>
  <created-by>jwhigginbotham</created-by>
  <created-on>November 18 2002</created-on>
  <priority>High</priority>
  <actor>member</actor>
  <feature>contentmanager</feature>
  <goal>Authenticate a user into the system</goal>
  <description>Allow a user who has an account to log into the system</description>
  <preconditions>
    <precondition>The member must have a valid account with the system</precondition>
  </preconditions>
  <postconditions>
    <postcondition>The member is marked as authenticated and logged into the system</postcondition>
    <postcondition>The system starts a new session for the member</postcondition>
  </postconditions>
  <!--
  <related-usecases>
    <related-usecase>CreateAccount</related-usecase>
    <related-usecase>ViewMemberHomepage</related-usecase>
  </related-usecases>
  -->
  <event-flow>
    <event>The member selects the login option</event>
    <event>The system prompts the member for their id and password</event>
    <event>The member provides a valid id and password</event>
    <event>The system determines the credentials are valid and log the member in</event>
    <event>The system presents the member with the content management homepage</event>
  </event-flow>
  <alternate-flow name="Bad Credentials">
    <event>The member enters bad credentials</event>
    <event>The system displays a message that the credentials are bad and offers the user another
    chance to login</event>
  </alternate-flow>
  <!--
  <alternate-flow name="Account disabled">
    <event>The system determines that the credentials entered are valid, but the account is
    disabled.</event>
    <event>The system informs the user that their account is disabled and offers an option to
    contact the site administrator</event>
  </alternate-flow>
  -->
  <alternate-flow name="Page requires authentication">
    <event>The system determines that the user requested a page that requires the user to be logged
    into the system</event>
    <event>The system performs the standard event flow (above).</event>
    <event>Instead of showing the user's homepage upon a successful login, the system takes the user
    to the previously requested page.</event>
  </alternate-flow>
</usecase>
